version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    template = '{{ .Icon }} '
 
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = '#BEBCAE'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style='full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }}{{ end }}{{ .HEAD }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'transparent'
    foreground = 'white'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'white'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = ' '
    background = 'transparent'
    foreground = 'white'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    template = ' {{ .Venv }}'
    background = 'transparent'
    foreground = 'white'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'red'
    background = 'transparent'
    template = '{{ if .Error }} ✗ {{ end }}'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#AC966D'
    background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#AC966D'
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground = 'white'
  background = 'transparent'
  template = '❯ '
