#!/usr/bin/env bash

# <config>
NUMBER=4
SYMBOL_CURRENT="  "
SYMBOLS_OTHER=("  " "  " "  " "  ")
PIPE=/tmp/workspace
WRAP=true
# </config>

trap "exit" SIGINT SIGTERM

# format_line takes the current workspace number [1..N] and prints a string
# representing the list of workspaces with distinct symbols for non-current workspaces
format_line() {
    local line=""
    for (( i=1; i<=$NUMBER; i++ )); do
        if [ $i -eq $1 ]; then
            line+="$SYMBOL_CURRENT "
        else
            line+="${SYMBOLS_OTHER[$i-1]} "
        fi
    done
    echo "$line"
}

# remove an existing pipe and make a new one
rm -f $PIPE
mkfifo $PIPE

# print initial state
current=1
format_line $current

while true
do
    if read input <$PIPE; then
        if [ "$input" == "right" ]; then input=$((current + 1)); fi
        if [ "$input" == "left" ]; then input=$((current - 1)); fi

        if (( $input < 1 )); then
            if [ "$WRAP" == "false" ]; then continue; fi
            input=$NUMBER
        fi
        if (( $input > $NUMBER )); then
            if [ "$WRAP" == "false" ]; then continue; fi
            input=1
        fi
        if (( $input == $current )); then continue; fi

        format_line $input
        current=$input
    fi
done
