# General settings
live_config_reload = true

# Imports
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

# Window settings
[window]
# opacity = 0.95
# blur = true
decorations = 'None'
padding = { x = 10, y = 10 }

[window.dimensions]
columns = 80
lines = 27


