theme = "monokai_transparent"

[editor]
line-number = 'relative'
bufferline = "always"
text-width = 200

[editor.statusline]
left = ["mode", "spinner", "separator"]
center = ["file-name","read-only-indicator","file-modification-indicator", "total-line-numbers"]
right = ["separator", "diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = true

[editor.auto-pairs]
'('=')'
'{'='}'
'['=']'
'"'='"'
'`'='`'
'<'='>'
"'"="'"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 20
wrap-at-text-width = true

[editor.indent-guides]
render = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
home = "no_op"
end = "no_op"


[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
home = "no_op"
end = "no_op"
